# Generated by Django 3.1.5 on 2021-01-25 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='address_ru',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='address_uz',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
