# Generated by Django 3.1.4 on 2021-01-13 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_auto_20210113_2344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sliders',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='sliders',
            name='updated_at',
        ),
    ]
