# Generated by Django 3.1.4 on 2021-01-13 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0010_auto_20210113_2346'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sliders',
        ),
    ]
