# Generated by Django 3.1.4 on 2021-01-13 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0011_delete_sliders'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='WoksImages',
        ),
    ]
